### ISSUE TITLE
Simple CRUD application in Django and HTML, CSS and JS

### ISSUE THREAD

**Issue by TheInspiredConjurer** [letdummy/Simple-to-Advance#11]
Hi. I would like to create a simple CRUD application using the aforementioned tech stack as part of Hacktoberfest,

Kindly assign me this issue as part of hacktoberfest.

Thanks.

**Comment by letdummy** [comment]
Hi thanks for your participation, can't wait for your update

**Comment by TheInspiredConjurer** [comment]
Why did you close this issue?

I'm still working on it.
