### ISSUE TITLE
GuessMyNumber_Game

### ISSUE THREAD

**Issue by akshit5565** [letdummy/Simple-to-Advance#113]
I wan to add my GuessMyNumber game under the Hacktoberfest.
Plz assign this task to me.

**Comment by akshit5565** [comment]
@letdummy plz assign me the task
Thanks!!

**Comment by letdummy** [comment]
your game would duplicate #17 that I already merge, I suggest you to upload another project, simple or advance level is allowed
hope you good with that

**Comment by letdummy** [comment]
Or you can try like #114 he rebrand Guess My Number name into  Spy Number Checker, make it easy for people to distinguish
