### ISSUE TITLE
Simon game

### ISSUE THREAD

**Issue by ola-nishant** [letdummy/Simple-to-Advance#116]
A fully responsive Simon Game, based on HTMl, CSS and Javascript

**Comment by letdummy** [comment]
I'm not familiar with simon game, but will love to have a look 🔥

**Comment by letdummy** [comment]
check my comment at #13 
but sure, I will add accepted tag here

**Comment by ola-nishant** [comment]
why is it showing not accepted on my hacktoberfest profile
