### ISSUE TITLE
Can I make a smart Pong game using HTML,CSS and JS?

### ISSUE THREAD

**Issue by bloodmonk7** [letdummy/Simple-to-Advance#13]
A game where you can play against the computer

**Comment by letdummy** [comment]
Sure you can, can't wait for your PR

**Comment by bloodmonk7** [comment]
Can you label it in hacktober, if you don't mind

**Comment by letdummy** [comment]
done, can't wait for your update
anyway, only PR/MRs counted as contribution in Hacktoberfest 2022, so don't forget to submit your PR/MRs ✌️
