### ISSUE TITLE
I Would Like To Add A Simple "Random Choice Picker" Project 

### ISSUE THREAD

**Issue by HridoyHazard** [letdummy/Simple-to-Advance#14]
I Would Like To Add A Simple "Random Choice Picker" Project  Using HTML,CSS,JS
Very Clean Code Ideal For Beginner

**Comment by HridoyHazard** [comment]
Here is the PR #16

**Comment by letdummy** [comment]
Checked it already, very cool project, after some configuration to the previous PR (#15) I will merge your PR ASAP, thank you ❤️
