### ISSUE TITLE
Add: Quiz App with Reactjs and Tailwind CSS

### ISSUE THREAD

**Issue by palashb01** [letdummy/Simple-to-Advance#146]
Features:

- MCQ Quiz App with sidebar and navbar
- Multiple Subjects Supported
- Correct & InCorrect Validation

**Comment by palashb01** [comment]
@letdummy Please Assign this Issue to me!

**Comment by letdummy** [comment]
Hi your project will duplicate #97  but if you still want to upload your quiz app, make sure your project name is unique 😇

**Comment by palashb01** [comment]
Hey @letdummy!! I will check that PR, and If found same will close this issue unless, will do the PR, Thanks.
