### ISSUE TITLE
BMI calculator

### ISSUE THREAD

**Issue by Vanshiii203** [letdummy/Simple-to-Advance#154]
**Is your feature request related to a problem? Please describe.**
I would like to make a BMI calculator using html CSS and JavaScript

**Comment by Aman1143** [comment]
Yes, I would like to make a BMI calculator using html CSS and JavaScript.

**Comment by letdummy** [comment]
Alright @Vanshiii203, sorry @Aman1143 but @Vanshiii203 create this issue and comment first, would love if you submit another object here 😇 hope you guys good with that
