### ISSUE TITLE
Dictionary Web App

### ISSUE THREAD

**Issue by Atharv-110** [letdummy/Simple-to-Advance#172]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Whenever we search something or write some content we just fed by remembering the words and their meanings so for that we should have some web app for finding meanings locally.
**Describe the solution you'd like**
I want to add an dictionary app made using JavaScript which fetches meaning of the word through an API and also it will have an additional feature of narration. We can also hear the word and meaning through speakers of our pc.
**Describe alternatives you've considered**
As an alternative we can use online dictionaries.
**Additional context**
![Screenshot_20221004-195443_Chrome](https://user-images.githubusercontent.com/87393095/193845431-04a1f4d9-9822-496f-8117-7b860585138d.jpg)

Consider this contribution under Hacktoberfest2022 and please assign this to me.

**Comment by letdummy** [comment]
Looking great, would be pleased to have this on the list 😇
