### ISSUE TITLE
JavaScript Password Validation

### ISSUE THREAD

**Issue by nileshlad09** [letdummy/Simple-to-Advance#19]
![image](https://user-images.githubusercontent.com/89249015/193439570-6def66e4-d844-4f79-9d46-62d577c7e3b8.png)
 
please assign this to me

**Comment by letdummy** [comment]
Hi, you can simply fork this repo, add your project, pull request and all done
only PR/MRs will be counted as contribution in Hacktoberfest 2022, so make sure you submit your PR ✌️

**Comment by nileshlad09** [comment]
done I submited PR
