### ISSUE TITLE
Basis Static webpage using HTML5

### ISSUE THREAD

**Issue by Prajwal0225** [letdummy/Simple-to-Advance#21]
I wanted to add a static webpage ( The timeline of Steve Jobs ) that I created only using HTML5

@letdummy Can you assign this issue to me?
                     So that I can add my project to this repo

**Comment by letdummy** [comment]
Can't wait for your update !! 🍻

**Comment by letdummy** [comment]
LGTM, nice and clean code, awesome
Will merge this ASAP after I finished merge previous PR, this won't effected your progress at Hacktoberfest2022
Thank you 👏

**Comment by Prajwal0225** [comment]
Thanks 😇
