### ISSUE TITLE
Rock, Paper, Scissor game using HTML,CSS and JS

### ISSUE THREAD

**Issue by Prajwal0225** [letdummy/Simple-to-Advance#23]
![rock pper](https://user-images.githubusercontent.com/103810119/193440760-eeceb58b-3ca7-4797-9662-b2d08b90ec90.png)

**Comment by vaibhavi-roy** [comment]
hey @Prajwal0225 I want to work on this issue.
Please assign this task to me.
Thank you

**Comment by vaibhavi-roy** [comment]
I have a query
Do you want me to make complete game in a new folder ?
I am unable to find the code in new folder.

**Comment by Ishika-jain** [comment]
Hey could you assign this to me?

**Comment by letdummy** [comment]
who will take this issue? @Prajwal0225 will you take it or pass it to another guy above?

**Comment by Prajwal0225** [comment]
I am taking it 😇

**Comment by letdummy** [comment]
noted
