### ISSUE TITLE
One page resturant site  for the college 

### ISSUE THREAD

**Issue by Omega12Pirme** [letdummy/Simple-to-Advance#52]
Hii i want to  submit the one page restaurant site for the college . 
That site contains the table booking about image gallery and much more . 
U can see   the images below 

![image](https://user-images.githubusercontent.com/105157723/193447393-64b3f9a0-970d-40eb-a480-1343aeb35ec3.png)

![image](https://user-images.githubusercontent.com/105157723/193447399-a015d815-9d61-46ef-b89a-35454e958aa2.png)

![image](https://user-images.githubusercontent.com/105157723/193447412-8735d349-247f-4533-a0c5-c1946b1fb97c.png)

![image](https://user-images.githubusercontent.com/105157723/193447419-aed2f2ea-1ef0-4e00-8d61-109d6f152f15.png)

## NOTE
I will also deploy this on the azure means creating+deploying will be done in this .

**Comment by test-account09** [comment]
I am also contributing under hacktoberfest

**Comment by letdummy** [comment]
your account name look anti-mainstream but nvm, happy coding

**Comment by test-account09** [comment]
Let me change my name @letdummy .  LOL  :laughing:

**Comment by letdummy** [comment]
LGTM, nice and clean code, awesome
Will merge this ASAP after I finished merge previous PR, this won't effected your progress at Hacktoberfest2022
Thank you 👏
