### ISSUE TITLE
Add pixi ball saver game.

### ISSUE THREAD

**Issue by toukirkhan** [letdummy/Simple-to-Advance#75]
I want add a ball saver game to this repo. Please assign me this repo.

**Comment by letdummy** [comment]
Can't wait for your update

**Comment by toukirkhan** [comment]
Hey I have submitted the project somewhere else just before you assigned me the issue. Can I submit the game here too?

**Comment by letdummy** [comment]
As long as there is no copyright issue, that will be fine

**Comment by toukirkhan** [comment]
It won't be considered as spam right?
I have contributed it another hacktoberfest repo too.

**Comment by letdummy** [comment]
based on this information https://hacktoberfest.com/participation/ 
your PR/MRs will only tagged as spam if and only if maintainers tagged your PR/MRs as a spam (and I will never tagged someone's PR as a spam)

**Comment by letdummy** [comment]
so I believe you good to do, if you good with that, I will not close this issue now and wait for your PR, thank you ❤️

**Comment by toukirkhan** [comment]
Can you keep this issue open for now? Let's wait for 5 days and if the
other PR is not accepted I will contribute here.

**Comment by letdummy** [comment]
Okay, I'm good with that

**Comment by toukirkhan** [comment]
Cool!
