### ISSUE TITLE
Need someone update README.md table content till number 35 (36-45 will be assigned in the next issue)

### ISSUE THREAD

**Issue by letdummy** [letdummy/Simple-to-Advance#92]
will assign this to one person and will merge it immediately, follow the previous template and I will check it manually

**Comment by hamzicio** [comment]
Hi , please assign this to me. Thankyou @letdummy

**Comment by hamzicio** [comment]
it doent have hactoberfest label

**Comment by styrene01** [comment]
I am up to do the task

**Comment by styrene01** [comment]
I have updated till no 35 with the folders that were done
